spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:file:./db/testdb;MODE=MYSQL"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console