spring:
  profiles:
    default: dev
    include: aws
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    password: marbox

jwt:
  header: access-token
  issuer: marbox
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 3600000 # 1시간 = 3,600,000ms

cloud:
  aws:
    s3:
      bucket: marbox-bucket
      save-dir-prefix: dev/
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false