spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marbox
    username: root
    password: root1234
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: MYSQL_DB

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: debug
  config: classpath:logback-${spring.config.activate.on-profile}.xml

cloud:
  aws:
    s3:
      bucket: marbox-bucket
      save-dir-prefix: dev/
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false