openapi: 3.0.1
info:
  title: Marbox API
  description: Marbox API description
  version: 1.0.0
servers:
- url: http://localhost:8080
tags: []
paths:
  /reservation:
    post:
      tags:
      - reservation
      operationId: reservation-create
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/reservation778141638'
            examples:
              reservation-create:
                value: "{\"userId\":1,\"scheduleId\":2,\"selectedSeatIds\":[3,4,5]}"
      responses:
        "201":
          description: "201"
  /reserved-seats/{scheduleId}:
    get:
      tags:
      - reserved-seats
      operationId: reserved-seat
      parameters:
      - name: scheduleId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reserved-seats-scheduleId1854644414'
              examples:
                reserved-seat:
                  value: "[{\"row\":0,\"col\":0,\"reserved\":false},{\"row\":0,\"\
                    col\":1,\"reserved\":true}]"
  /schedules:
    post:
      tags:
      - schedules
      operationId: schedule-save
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/schedules266360835'
            examples:
              schedule-save:
                value: "{\"theaterRoomId\":1,\"movieId\":1,\"startTime\":\"2022-07-14T16:37:29.573038\"\
                  ,\"endTime\":\"2022-07-14T16:37:29.573058\"}"
      responses:
        "201":
          description: "201"
  /schedules/current-movies:
    get:
      tags:
      - schedules
      operationId: schedule-get-current-movies
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/schedules-current-movies1672648316'
              examples:
                schedule-get-current-movies:
                  value: "[{\"name\":\"테스트1\",\"limitAge\":\"CHILD\",\"genre\":\"\
                    ACTION\",\"runningTime\":100,\"posterImgLocation\":\"test/location\"\
                    },{\"name\":\"테스트2\",\"limitAge\":\"CHILD\",\"genre\":\"ROMANCE\"\
                    ,\"runningTime\":150,\"posterImgLocation\":\"test/location\"},{\"\
                    name\":\"테스트3\",\"limitAge\":\"ADULT\",\"genre\":\"ACTION\",\"\
                    runningTime\":120,\"posterImgLocation\":\"test/location\"}]"
  /schedules/search:
    get:
      tags:
      - schedules
      operationId: schedule-get-
      parameters:
      - name: theaterId
        in: query
        description: 영화관 ID
        required: false
        schema:
          type: string
      - name: date
        in: query
        description: 날짜
        required: false
        schema:
          type: string
      - name: movieId
        in: query
        description: 영화 ID
        required: false
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/schedules-search588914321'
              examples:
                schedule-get-movie-and-date-in-theater:
                  value: "{\"movieList\":[{\"name\":\"영화1\",\"limitAge\":\"CHILD\"\
                    ,\"genre\":\"ACTION\",\"runningTime\":100,\"posterImgLocation\"\
                    :\"test/location\"},{\"name\":\"영화2\",\"limitAge\":\"ADULT\",\"\
                    genre\":\"ROMANCE\",\"runningTime\":120,\"posterImgLocation\"\
                    :\"test/location\"},{\"name\":\"영화3\",\"limitAge\":\"CHILD\",\"\
                    genre\":\"ANIMATION\",\"runningTime\":150,\"posterImgLocation\"\
                    :\"test/location\"}],\"theaterList\":[],\"dateList\":[\"2022-07-14\"\
                    ,\"2022-07-15\"],\"timeList\":[]}"
                schedule-get-movie-by-date-and-theater:
                  value: "{\"movieList\":[{\"name\":\"영화1\",\"limitAge\":\"CHILD\"\
                    ,\"genre\":\"ACTION\",\"runningTime\":100,\"posterImgLocation\"\
                    :\"test/location\"},{\"name\":\"영화2\",\"limitAge\":\"ADULT\",\"\
                    genre\":\"ROMANCE\",\"runningTime\":120,\"posterImgLocation\"\
                    :\"test/location\"},{\"name\":\"영화3\",\"limitAge\":\"CHILD\",\"\
                    genre\":\"ANIMATION\",\"runningTime\":150,\"posterImgLocation\"\
                    :\"test/location\"}],\"theaterList\":[],\"dateList\":[],\"timeList\"\
                    :[]}"
                schedule-get-timeList-by-movie-and-theater-and-date:
                  value: "{\"movieList\":[],\"theaterList\":[],\"dateList\":[],\"\
                    timeList\":[{\"theaterRoomName\":\"상영관1\",\"totalSeatCount\":75,\"\
                    startTimeList\":[\"09:30:00\",\"14:25:00\",\"16:45:00\",\"19:30:00\"\
                    ]},{\"theaterRoomName\":\"상영관2\",\"totalSeatCount\":100,\"startTimeList\"\
                    :[\"20:40:00\"]}]}"
  /theater-rooms:
    post:
      tags:
      - theater-rooms
      operationId: theater-room-save
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/theater-rooms-1243494910'
            examples:
              theater-room-save:
                value: "{\"theaterId\":1,\"name\":\"A관\",\"requestCreateSeats\":[{\"\
                  row\":0,\"col\":1},{\"row\":0,\"col\":0}]}"
      responses:
        "201":
          description: "201"
  /theaters:
    get:
      tags:
      - theaters
      operationId: theater-find-all
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/theaters-region486549215'
              examples:
                theater-find-all:
                  value: "[{\"region\":\"SEOUL\",\"theaterName\":\"theater0\"},{\"\
                    region\":\"SEOUL\",\"theaterName\":\"theater1\"},{\"region\":\"\
                    SEOUL\",\"theaterName\":\"theater2\"},{\"region\":\"SEOUL\",\"\
                    theaterName\":\"theater3\"},{\"region\":\"SEOUL\",\"theaterName\"\
                    :\"theater4\"},{\"region\":\"SEOUL\",\"theaterName\":\"theater5\"\
                    },{\"region\":\"SEOUL\",\"theaterName\":\"theater6\"},{\"region\"\
                    :\"SEOUL\",\"theaterName\":\"theater7\"},{\"region\":\"SEOUL\"\
                    ,\"theaterName\":\"theater8\"},{\"region\":\"SEOUL\",\"theaterName\"\
                    :\"theater9\"}]"
    post:
      tags:
      - theaters
      operationId: theater-save
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/theaters582794890'
            examples:
              theater-save:
                value: "{\"region\":\"SEOUL\",\"name\":\"theater0\"}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/theaters-theaterId1673730357'
              examples:
                theater-save:
                  value: "{\"region\":\"SEOUL\",\"theaterName\":\"theater0\"}"
  /theaters/region:
    get:
      tags:
      - theaters
      operationId: theater-find-by-region
      parameters:
      - name: name
        in: query
        description: 지역
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/theaters-region486549215'
              examples:
                theater-find-by-region:
                  value: "[{\"region\":\"SEOUL\",\"theaterName\":\"theater0\"}]"
  /theaters/{theaterId}:
    get:
      tags:
      - theaters
      operationId: theater-find
      parameters:
      - name: theaterId
        in: path
        description: 영화관 ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/theaters-theaterId1673730357'
              examples:
                theater-find:
                  value: "{\"region\":\"SEOUL\",\"theaterName\":\"theater0\"}"
  /users/refresh:
    post:
      tags:
      - users
      operationId: user-refresh
      responses:
        "204":
          description: "204"
          headers:
            Set-Cookie:
              description: "new access token, new refresh token"
              schema:
                type: string
  /users/sign-in:
    post:
      tags:
      - users
      operationId: user-sign-in
      parameters:
      - name: Content-Type
        in: header
        description: 컨텐츠 타입
        required: true
        schema:
          type: string
        example: application/json;charset=UTF-8
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/users-sign-in32710318'
            examples:
              user-sign-in:
                value: "{\"email\":\"pang@mail.com\",\"password\":\"1234\"}"
      responses:
        "204":
          description: "204"
          headers:
            Set-Cookie:
              description: 쿠키 세팅
              schema:
                type: string
  /users/sign-up:
    post:
      tags:
      - users
      operationId: user-sign-up
      parameters:
      - name: Content-Type
        in: header
        description: 컨텐츠 타입
        required: true
        schema:
          type: string
        example: application/json;charset=UTF-8
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/users-sign-up2102361656'
            examples:
              user-sign-up:
                value: "{\"email\":\"pang@mail.com\",\"password\":\"1234\",\"name\"\
                  :\"pang\",\"role\":\"ROLE_ADMIN\"}"
      responses:
        "201":
          description: "201"
          headers:
            Location:
              description: 로그인 API 위치
              schema:
                type: string
components:
  schemas:
    theater-rooms-1243494910:
      type: object
      properties:
        theaterId:
          type: number
          description: 영화관 id
        name:
          type: string
          description: 상영관 이름
        requestCreateSeats:
          type: array
          items:
            type: object
            properties:
              col:
                type: number
                description: 열
              row:
                type: number
                description: 행
    schedules266360835:
      type: object
      properties:
        theaterRoomId:
          type: number
          description: 상영관 ID
        startTime:
          type: string
          description: 영화 시작 날짜와 시간
        movieId:
          type: number
          description: 영화 ID
        endTime:
          type: string
          description: 영화 종료 날짜와 시간
    reserved-seats-scheduleId1854644414:
      type: array
      items:
        type: object
        properties:
          col:
            type: number
            description: 열
          reserved:
            type: boolean
            description: 예약 유무
          row:
            type: number
            description: 행
    theaters-theaterId1673730357:
      type: object
      properties:
        theaterName:
          type: string
          description: 영화관 이름
        region:
          type: string
          description: 지역
    theaters582794890:
      type: object
      properties:
        name:
          type: string
          description: 영화관 이름
        region:
          type: string
          description: 지역
    reservation778141638:
      type: object
      properties:
        userId:
          type: number
          description: 유저 ID
        scheduleId:
          type: number
          description: 스케줄 ID
        selectedSeatIds:
          type: array
          description: 선택한 좌석
          items:
            oneOf:
            - type: object
            - type: boolean
            - type: string
            - type: number
    users-sign-up2102361656:
      type: object
      properties:
        password:
          type: string
          description: 사용자 비밀번호
        role:
          type: string
          description: 사용자 역할
        name:
          type: string
          description: 사용자 이름
        email:
          type: string
          description: 사용자 이메일
    schedules-search588914321:
      type: object
      properties:
        theaterList:
          type: array
          description: 빈 배열
          items:
            oneOf:
            - type: object
            - type: boolean
            - type: string
            - type: number
        timeList:
          type: array
          description: 상영 시간 정보
          items:
            type: object
            properties:
              startTimeList:
                type: array
                description: 상영관의 영화 시작 시간 배열
                items:
                  oneOf:
                  - type: object
                  - type: boolean
                  - type: string
                  - type: number
              theaterRoomName:
                type: string
                description: 상영관 이름
              totalSeatCount:
                type: number
                description: 상영관 총 좌석 수
        dateList:
          type: array
          description: 빈 배열
          items:
            oneOf:
            - type: object
            - type: boolean
            - type: string
            - type: number
        movieList:
          type: array
          description: 빈 배열
          items:
            type: object
            properties:
              posterImgLocation:
                type: string
                description: 포스터 이미지 경로
              genre:
                type: string
                description: 장르
              name:
                type: string
                description: 영화 이름
              runningTime:
                type: number
                description: 상영시간
              limitAge:
                type: string
                description: 영화 관람 등급
    users-sign-in32710318:
      type: object
      properties:
        password:
          type: string
          description: 사용자 비밀번호
        email:
          type: string
          description: 사용자 이메일
    schedules-current-movies1672648316:
      type: array
      items:
        type: object
        properties:
          posterImgLocation:
            type: string
            description: 포스터 이미지 경로
          genre:
            type: string
            description: 장르
          name:
            type: string
            description: 영화 이름
          runningTime:
            type: number
            description: 상영시간
          limitAge:
            type: string
            description: 연령 제한
    theaters-region486549215:
      type: object
